export { Page } from './src/components/Page';
export { Seo } from './src/components/Seo';
export { HeroSection } from './src/sections/Hero';
export { ArticlesSection } from './src/sections/Articles';
export { AboutSection } from './src/sections/About';
export { InterestsSection } from './src/sections/Interests';
export { ProjectsSection } from './src/sections/Projects';
export { ContactSection } from './src/sections/Contact';
export { LegalSection } from './src/sections/Legal';
